### ISSUE TITLE
New commits not triggering another bot run

### ISSUE THREAD

**Issue by grantjk** [modcloth-labs/github-xcode-bot-builder#7]
First off, this made my Monday! I found this on the weekend, implemented it this morning and am super excited to use it!

One thing I noticed today is that when a new commit is given to a PR that already has a bot run on it, a new comment is posted immediately by the bot-builder without triggering a new run on the bot.  I would expect that the PR would be updated to "Pending" and a bot run would be queued.

Here's a copy of the logs:
## Starting Github Xcode Bot Builder 2014-04-14 14:32:02 -0400

PR 298 (success) is up to date for bot 298
PR 297 (success) is up to date for bot 297
PR 278 (success) is up to date for bot 278
## PR 255 (failure) is up to date for bot 255

Finished Github Xcode Bot Builder 2014-04-14 14:32:03 -0400
## Starting Github Xcode Bot Builder 2014-04-14 14:34:02 -0400

PR 298 (success) is up to date for bot 298
PR 297 (success) is up to date for bot 297
PR 278 added comment "Build Success: Succeeded.
http://0.0.0.0/xcode/bots/278"
PR 278 status updated to "success" with description "Succeeded."
## PR 255 (failure) is up to date for bot 255

Finished Github Xcode Bot Builder 2014-04-14 14:34:04 -0400

**Comment by geoffnix** [comment]
Thanks!  Yes, we've noticed this issue as well.  We don't have a fix yet, but in the meantime you can got to the bot interface in your browser and click "integration now".

**Comment by grantjk** [comment]
Thanks. Looking forward to the fix. Let me know if I can help
